
from Configurations import Configurations
from utils import *
from utils import Logs
from utils import CalcTime
import streamlit as st
from gptAPI import app
from dalleapi import dalle
from PIL import Image
import urllib.request

class inference_genAI(Configurations):

    def __init__(self):
        super().__init__()
        self.logs = Logs()
        self.timer = CalcTime()
        self.query = app.gptquery()
        self.dalle = dalle.dallEapi()
        self.load_streamlit()

    def __call__(self):
        self.timer.start()
        self.timer.end()
        self.logs.UpdateLogs("Time took to process Query :" + str(self.timer.calculate()) + "s" )

    def load_streamlit(self):
        st.title("Generate Text/Image using Generative AI Models")
        prompt = st.text_area("Enter the message")
        self.logs.UpdateLogs("Input Query is:" + prompt)
        if st.button('Generate Text'):
            gentext = self.query.openAIQuery(prompt)
            self.logs.UpdateLogs("Output Answer s:" + gentext)
            st.header(gentext)
        if st.button('Generate Image'):
            genimage = self.dalle.dallEquery(prompt)
            st.header(prompt)
            urllib.request.urlretrieve(genimage, "Imagegen.png")
            image = Image.open("Imagegen.png")
            st.image(image, caption='Generated By Dall E')
            

if __name__ == "__main__":
    inference = inference_genAI()
    inference()
    